comm_range: 100
data_augment:
- ALONG_AXIS_LIST:
  - x
  NAME: random_world_flip
- NAME: random_world_rotation
  WORLD_ROT_ANGLE:
  - -0.78539816
  - 0.78539816
- NAME: random_world_scaling
  WORLD_SCALE_RANGE:
  - 0.95
  - 1.05
data_dir: /path/to/dataset/DAIR-V2X/cooperative-vehicle-infrastructure
fusion:
  args:
    proj_first: true
  core_method: DAIRV2XIntermediateFusionDataset
input_source:
- lidar
label_type: lidar
loss:
  args:
    feature_map_stride: 8
    grid_size: &id001 !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - !!python/name:numpy.ndarray ''
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple
        - 3
      - !!python/object/apply:numpy.dtype
        args:
        - i8
        - false
        - true
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - false
      - !!binary |
        AAQAAAAAAAAABAAAAAAAACgAAAAAAAAA
    loss_config:
      code_weights:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      loss_cls:
        alpha: 0.25
        gamma: 2.0
        use_sigmoid: true
      loss_weights:
        bbox_weight: 2.0
        cls_weight: 1.0
        hm_weight: 1.0
        ortho_weight: 1.0
        vq_weight: 1.0
    max_cav: 2
    num_classes: 1
    point_cloud_range: &id002
    - -102.4
    - -102.4
    - -10
    - 102.4
    - 102.4
    - 6
    post_processing:
      post_center_range: &id004
      - -102.4
      - -102.4
      - -10
      - 102.4
      - 102.4
      - 6
      score_thresh: 0.0
    target_assigner_config:
      feature_map_stride: 8
      gaussian_overlap: 0.1
      hungarian_assigner:
        cls_cost:
          alpha: 0.25
          gamma: 2.0
          weight: 0.15
        iou_cost:
          weight: 0.25
        reg_cost:
          weight: 0.25
      min_radius: 2
    voxel_size: &id003
    - 0.2
    - 0.2
    - 0.4
  core_method: focal_loss
model:
  args:
    backbone_3d: []
    base_bev_backbone:
      layer_nums:
      - 5
      - 5
      layer_strides:
      - 1
      - 2
      num_filters:
      - 128
      - 256
      num_upsample_filter:
      - 256
      - 256
      upsample_strides:
      - 1
      - 2
      use_conv_for_no_stride: true
    batch_size: 8
    cobevt:
      agent_size: 2
      depth: 3
      dim_head: 32
      drop_out: 0.1
      input_dim: 256
      mlp_dim: 256
      window_size: 4
    compression:
      beta_commit: 0.05
      channel_reduction_ratio: 16
      codebook_size: 256
      compression_method: ChannelRVQ_EMA
      ema_decay: 0.8
      n_q: 3
      ortho_reg: 0.0001
      ortho_weight: 1.0
      use_groupnorm: true
      vq_weight: 1.0
    dense_head:
      activation: relu
      bn_momentum: 0.1
      class_agnostic: false
      dataset_name: dairv2x
      dropout: 0.1
      feature_map_stride: 8
      ffn_channel: 256
      grid_size: *id001
      hidden_channel: 128
      input_channels: 256
      nms_kernel_size: 3
      num_class: 1
      num_heads: 4
      num_hm_conv: 2
      num_proposals: 300
      separate_head_cfg:
        head_dict:
          center:
            num_conv: 2
            out_channels: 2
          dim:
            num_conv: 2
            out_channels: 3
          height:
            num_conv: 2
            out_channels: 1
          rot:
            num_conv: 2
            out_channels: 2
        head_order:
        - center
        - height
        - dim
        - rot
    fusion_method: cobevt
    grid_size: *id001
    height_compression:
      feature_num: 256
    in_head: 256
    lidar_range: *id002
    max_cav: 2
    mean_vfe:
      feature_points: 4
    num_classes: 1
    voxel_size: *id003
  core_method: cobevt
name: dair_cobevt_revqom_k256_nq3_crr16_ema08_refq
noise_setting: !!python/object/apply:collections.OrderedDict
- - - add_noise
    - false
optimization:
  batch_size_per_gpu: 8
  betas:
  - 0.9
  - 0.999
  decay_step_list:
  - 35
  - 45
  div_factor: 10
  grad_norm_clip: 35
  lr: 0.001
  lr_clip: 1.0e-07
  lr_decay: 0.1
  lr_warmup: false
  momentum: 0.9
  moms:
  - 0.9
  - 0.8052631
  num_epochs: 30
  optimizer: adam_onecycle
  pct_start: 0.4
  warmup_epoch: 1
  weight_decay: 0.01
postprocess:
  cav_lidar_range: *id002
  core_method: FocalCommPostprocessor
  feature_map_stride: 8
  max_num: 400
  nms_thresh: 0.15
  num_classes: 1
  order: hwl
  post_center_range: *id004
  score_threshold: 0.1
  voxel_size: *id003
preprocess:
  args:
    max_points_per_voxel: 20
    max_voxel_test: 144000
    max_voxel_train: 72000
    voxel_size: *id003
  cav_lidar_range: *id002
  core_method: SpVoxelPreprocessor
  num_class: 1
root_dir: /path/to/dataset/DAIR-V2X/cooperative-vehicle-infrastructure/train.json
test_dir: /path/to/dataset/DAIR-V2X/cooperative-vehicle-infrastructure/val.json
train_params:
  batch_size: 8
  epoches: 30
  eval_freq: 1
  max_cav: 2
  save_freq: 1
validate_dir: /path/to/dataset/DAIR-V2X/cooperative-vehicle-infrastructure/val.json
yaml_parser: load_anchor_free_params
